SELECT 
    INCIDENT_TYPE,
    COUNT(*) AS TOTAL_INCIDENTS
FROM INCIDENT_REPORTS
GROUP BY INCIDENT_TYPE
ORDER BY TOTAL_INCIDENTS DESC;

SELECT 
    PRIORITY_LEVEL,
    COUNT(*) AS TOTAL_PRIORITY_CASES
FROM INCIDENT_REPORTS
GROUP BY PRIORITY_LEVEL;

SELECT 
    STATUS,
    COUNT(*) AS TOTAL_STATUS_COUNT
FROM INCIDENT_REPORTS
GROUP BY STATUS;